// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmfyzafraowiukqksuee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtZnl6YWZyYW93aXVrcWtzdWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzk5NTgsImV4cCI6MjA2MjYxNTk1OH0.bnswe3Wqd--OJvYIoYX-DNOHaMGEqZch26Rot3_xQAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);